### ISSUE TITLE
error in demo.m: pooling window is larger than the DATA

### ISSUE THREAD

**Issue by ZiyangLiu** [igondia/matconvnet-dermoscopy#1]
Hello, 
I try to run demo.m
It has the following error: 

Computing the diagnosis
Error using vl_nnpool
The pooling window is larger than the DATA (including padding).
Error in dagnn.Pooling/forward (line 10)
      outputs{1} = vl_nnpool(inputs{1}, self.poolSize, ...
Error in dagnn.Layer/forwardAdvanced (line 85)
      outputs = obj.forward(inputs, {net.params(par).value}) ;
Error in dagnn.DagNN/eval (line 92)
  obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;
Error in demo (line 109)
    net.eval(sinputs);

Do you know how to fix this? 
Thank you very much.

**Comment by igondia** [comment]
Hi,

in my last commit, the diagnosis network file had some errors in meta-data definition, particularly in the image sizes (which is supposed to be 256x256 and not 224x244 as in the original resnet-50). It should be fixed now.

Iván

**Comment by ZiyangLiu** [comment]
Thank you very much. It works now.
