### ISSUE TITLE
In cnn_train_dag_mod.m, Unknown training method 'notrain' for parameter 'wmods'.

### ISSUE THREAD

**Issue by ZiyangLiu** [igondia/matconvnet-dermoscopy#2]
Hello, 
I want to try trainDiagnosisNet.m. 
It reports the error in cnn_train_dag_mod.m:
Error using cnn_train_dag_mod>accumulateGradients
Unknown training method 'notrain' for parameter 'wmods'.

In accumulateGradients, switch net.params(p).trainMethod, there are two cases: 
'average' and 'gradient', but no 'notrain'
It seems there should be a new case for 'notrain'

Do you know how to fix this? 
Thank you very much.

**Comment by igondia** [comment]
Hi:

It should be fixed now.
Iván

**Comment by ZiyangLiu** [comment]
Thank you very much
